server:
  port: 9993

spring:
  kafka:
    bootstrap-servers: http://localhost:9092
    task:
      scheduler:
        period: 20000
    producer:
      client-id: server-third
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 2
      topic: OMS_TEMP
      key: IN_KEY

test:
  value: This is weather station Third